### ISSUE TITLE
Design/Evaluate Supporting Project-scoped apikeys

### ISSUE THREAD

**Issue by jasonmimick** [mongodb/atlas-osb#42]
In order to support more secure deployment scenarios, this ticket will track discussions and design to add support for "Project-scoped" apikeys. This is motivated by customer asks:

+ Allow admins to offer services which are scoped to static project and apikeys
+ Support DEV/PROD project boundaries
+ Remove need for "maintenance" project which crosses project-boundaries

We will determine if support for these scenarios is feasible through this issue discussion.

**Comment by vasilevp** [comment]
This is _mostly_ supported by the Broker. Here are the changes we'll need to make to get this working:
- Make Org Credentials optional, since API Keys can be hard-coded in plan templates (and, in this case, they should be) - _might not be necessary, just use a Project key in Credentials_
- Disable Project cleanup when a Project is hard-coded in template
  - Deduce this in code _(will need to come up with a way to figure this out - could be complicated)_
  OR
  - Allow the user to turn it off _(trivial)_
- Allow for the State Storage to be created inside the hard-coded Project when we have one
  - Deduce ... _(same logic as above)_
  - Allow the user to override a Project ID for State Storage _(trivial)_
- Currently, DatabaseUser and IPWhitelists are only added on project creation - need to change this to try and add them on every provision, and if found, do nothing _(backwards-compatible, minimal work needed)_

Here's an idea of what a plan template might look like in this scenario:
```yaml
name: restricted-to-one-project
# ...

apiKey: {{ keyByAlias .credentials "myProjectKey" }} # REQUIRED: this is a Project key, not an Org one
# or even
apiKey:
  publicKey: abcdef123456
  privateKey: aaaaa-aaaaa-aaaaa-aaaaa-aaaaa

project:
  name: {{ .instance_name }}
  id: abcdef123456 # REQUIRED: if Project.ID is hardcoded, the Broker won't create a new project

cluster:
  # same as before

databaseUsers:
- username: {{ cat "user-" .instance_name }} # will be "user-myInstanceName" - unique for each instance
  # or just
  username: {{ uuidv4 }} # pretty unique but not human-readable
  # everything else can be same as before

ipWhitelists:
  # same as before
```
